exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/getint.lsp | xxd
set stty_init "raw -echo"

spawn node src/main.js --no-dcl test/getint.lsp

set timeout 5

expect "^Test #1\n"
expect "^Press return: "
send "\r"
expect {
    "^<|nil|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect "^Enter int: "
send "abcd\r"
expect {
    "^Requires an integer value\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Enter int: "
send "123\r"
expect {
    "^<|123|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
send "456\r"
expect {
    "^<|456|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
