exp_internal 1

# Behave like in bash: don't replace \n with \r\n and don't echo
set stty_init "raw -echo"

spawn node src/main.js test/getreal.lsp

set timeout 5

expect "^Test #1\n"
expect "^Press return: "
send "\r"
expect {
    "^<|nil|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect "^Enter real: "
send "abcd\r"
expect {
    "^Requires numeric value\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Enter real: "
send "123\r"
expect {
    "^<|123.0|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
send "456.7\r"
expect {
    "^<|456.7|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
