exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/getstring.lsp | xxd
set stty_init "raw -echo"

spawn node src/main.js --no-dcl test/getstring.lsp

set timeout 5

expect "^Test #1\n"
send "\r"
expect {
    "^<||>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
send " \r"
# Breaks on SP and drops CR
expect {
    "^<||>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
send "abc def\r"
expect {
    "^<|abc|>\n<|def|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #4\n"
expect "^SP and CR: "
send "abc def\r"
expect {
    "^<|abc|>\n<|def|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #5\n"
expect "^SP and CR: "
send "abc def\r"
expect {
    "^<|abc|>\n<|def|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #6\n"
expect "^CR: "
send "abc def\r"
expect {
    "^<|abc def|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
