# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/princ.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/princ.lsp

# Allow some garbage before "Test"
expect "Test #1\n"
expect {
    "^" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect {
    "^\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
expect {
    "^Hello: " {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #4\n"
expect {
    "^Hello: \n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #5\n"
expect {
    "^<| \" \r \n \t |>" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #6\n"
expect {
    "^nil" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #7\n"
expect {
    "^(1 \"2\" '3)" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
