exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/print.lsp | xxd
set stty_init "raw -echo"

spawn node src/main.js --no-dcl test/print.lsp

set timeout 5

# Linux   EOL is \n
# Windows EOL is \r\n

expect "^Test #1\n"
expect {
    "^\n\"\" "   {}
    "^\r\n\"\" " {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect {
    "^\n\"\" "   {}
    "^\r\n\"\" " {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
expect {
    "^\nnil "   {}
    "^\r\nnil " {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #4\n"
expect {
    "^\n(1 \"2\" '3) "   {}
    "^\r\n(1 \"2\" '3) " {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
