exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js test/prompt.lsp | xxd
set stty_init "raw -echo"

spawn node src/main.js test/prompt.lsp

set timeout 5

expect "^Test #1\n"
expect {
    "^" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect {
    "^\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
expect {
    "^Hello: " {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #4\n"
expect {
    "^Hello: \n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #5\n"
expect {
    "^<| \" \r \n \t |>" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
