exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js test/read-line.lsp | xxd
set stty_init "raw -echo"

spawn node src/main.js test/read-line.lsp

set timeout 5

send "Line 1\r"
expect {
    "^<|Line 1|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

send "Line 2\rLine 3\r"
expect {
    "^<|Line 2|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^<|Line 3|>\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
