# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/trace.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/trace.lsp

# Allow some garbage before "Test"
expect "Test #1\n"
set lines {
    "^0: Entering (POWER 3 4)\n"
    "^  1: Entering (POWER 3 3)\n"
    "^    2: Entering (POWER 3 2)\n"
    "^      3: Entering (POWER 3 1)\n"
    "^        4: Entering (POWER 3 0)\n"
    "^        4: Result: 1\n"
    "^      3: Result: 3\n"
    "^    2: Result: 9\n"
    "^  1: Result: 27\n"
    "^0: Result: 81\n"
    "^81\n"
}
foreach line $lines {
    expect {
        $line {}
        timeout {exit 1}
        eof {exit 2}
    }
}

expect "^Test #2\n"
expect {
    "^81\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
set lines {
    "^0: Entering (FIBONACCI 3)\n"
    "^  1: Entering (FIBONACCI 2)\n"
    "^    2: Entering (FIBONACCI 1)\n"
    "^    2: Result: 1\n"
    "^    2: Entering (FIBONACCI 0)\n"
    "^    2: Result: 1\n"
    "^  1: Result: 2\n"
    "^  1: Entering (FIBONACCI 1)\n"
    "^  1: Result: 1\n"
    "^0: Result: 3\n"
    "^3\n"
}
foreach line $lines {
    expect {
        $line {}
        timeout {exit 1}
        eof {exit 2}
    }
}

exit 0
