# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/trace.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/trace.lsp

# Allow some garbage before "Test"
expect "Test #1\n"
expect {
    "^0: Entering (POWER 3 4)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Entering (POWER 3 3)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Entering (POWER 3 2)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^      3: Entering (POWER 3 1)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^        4: Entering (POWER 3 0)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^        4: Result: 1\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^      3: Result: 3\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Result: 9\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Result: 27\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^0: Result: 81\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^81\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #2\n"
expect {
    "^81\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect "^Test #3\n"
expect {
    "^0: Entering (FIBONACCI 3)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Entering (FIBONACCI 2)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Entering (FIBONACCI 1)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Result: 1\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Entering (FIBONACCI 0)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^    2: Result: 1\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Result: 2\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Entering (FIBONACCI 1)\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^  1: Result: 1\n" {}
    timeout {exit 1}
    eof {exit 2}
}
expect {
    "^0: Result: 3\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
