# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/write-line.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/write-line.lsp

# Linux   EOL is \n
# Windows EOL is \r\n

# Allow some garbage before "Test"
expect "Test #1\n"
expect {
    "^<|Line 1|>\n"   {}
    "^<|Line 1|>\r\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect {
    "^<|Line 2|>\n"   {}
    "^<|Line 2|>\r\n" {}
    timeout {exit 1}
    eof {exit 2}
}

expect {
    "^<|Line 3|>\n"   {}
    "^<|Line 3|>\r\n" {}
    timeout {exit 1}
    eof {exit 2}
}

exit 0
