# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/stacktrace/foreach/test1.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/stacktrace/foreach/test1.lsp

set lines {
    "^Error: apply: no such function nil\n"
    "^    at CALL_FUN (*/test1.lsp:4)\n"
    "^    at MAIN (*/test1.lsp:8)\n"
    "^    at */test1.lsp:10\n"
}

foreach line $lines {
    expect {
        $line {}
        timeout {exit 1}
        eof {exit 2}
    }
}

exit 0
