#!/usr/bin/env bash

# Debug libs loading
[[ "${VELISP_DEBUG}" == "libs" ]] && export DYLD_PRINT_LIBRARIES=1

# Force local homebrew/lib
BASE_DIR=$(dirname $0)

DYLD_LIBRARY_PATH=$BASE_DIR/homebrew/lib
GI_TYPELIB_PATH=$BASE_DIR/homebrew/lib/girepository-1.0

case $(sw_vers -productVersion) in
10.15* | 11.*) # Catalina, Big Sur
    # Symbol not found: __cg_jpeg_resync_to_restart
    DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources:$DYLD_LIBRARY_PATH
    ;;
*)
    ;;
esac

export DYLD_LIBRARY_PATH
export GI_TYPELIB_PATH

exec $BASE_DIR/velisp.bin "$@"
