#!/usr/bin/env bash

# Debug libs loading
[[ "${VELISP_DEBUG}" == "libs" ]] && export DYLD_PRINT_LIBRARIES=1

# Force local homebrew/lib
BASE_DIR=$(dirname $0)
export DYLD_LIBRARY_PATH=$BASE_DIR/homebrew/lib
export GI_TYPELIB_PATH=$BASE_DIR/homebrew/lib/girepository-1.0

exec $BASE_DIR/velisp.bin "$@"
