#!/usr/bin/env bash

# Propagate if set
export DYLD_PRINT_LIBRARIES=$DYLD_PRINT_LIBRARIES

# Force local homebrew/lib
BASE_DIR=$(dirname $0)
export DYLD_LIBRARY_PATH=$BASE_DIR/homebrew/lib
export GI_TYPELIB_PATH=$BASE_DIR/homebrew/lib/girepository-1.0

exec $BASE_DIR/velisp.bin "$@"
