# Enable diagnostic output
exp_internal 1

# Don't replace \n with \r\n and don't echo
# Behaves like:
# $ node src/main.js --no-dcl test/stacktrace/test1/main.lsp | xxd
set stty_init "raw -echo"
set timeout 5

spawn node src/main.js --no-dcl test/stacktrace/test1/main.lsp

# Allow some garbage before "Error"
set lines {
    "Error: +: expected Int, Real\n"
    "^    at ADD (*second.lsp:6)\n"
    "^    at DOUBLE (*second.lsp:3)\n"
    "^    at F1 (*first.lsp:4)\n"
    "^    at *main.lsp:3\n"
}

foreach line $lines {
    expect {
        $line {}
        timeout {exit 1}
        eof {exit 2}
    }
}

exit 0
