(defun toggle ( / btn_label)
   (setq label (get_tile "toggle"))
   (cond ((= label "Disable")
            (mode_tile "edit1" TILE_MODE_DISABLE)
            (set_tile "toggle" "Enable"))
         ((= label "Enable")
            (mode_tile "edit1" TILE_MODE_ENABLE)
            (set_tile "toggle" "Focus"))
         ((= label "Focus")
            (mode_tile "edit1" TILE_MODE_FOCUS)
            (set_tile "toggle" "Disable"))))

(action_tile "toggle" "(toggle)")
(action_tile "cancel" "(done_dialog 0)")
