;;;; SPDX-License-Identifier: 0BSD

(setq TILE_MODE_ENABLE 0)
(setq TILE_MODE_DISABLE 1)
(setq TILE_MODE_FOCUS 2)
(setq TILE_MODE_SELECT_EDITBOX 3)
(setq TILE_MODE_FLIP_IMAGE_HIGHLIGHT 4)

(setq START_LIST_CHANGE 1)
(setq START_LIST_APPEND 2)
(setq START_LIST_CLEAR 3)

(setq ACTION_REASON_SELECTED 1)
(setq ACTION_REASON_FOCUS_LOST 2)
(setq ACTION_REASON_INTERIM_CHANGE 3)
(setq ACTION_REASON_DOUBLE_CLICK 4)
